# -*- coding: utf-8 -*-
"""lyrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14A5-c8FATQMLlETQPJwVS0tgw6NLBNKx
"""

# Cell 1: Mount Drive and Install Dependencies
from google.colab import drive
drive.mount('/content/drive')

!pip install -q openai-whisper
!sudo apt update && sudo apt install ffmpeg -y

print("✓ Setup complete!")

# Cell 2: Import Libraries
import whisper
import os
import numpy as np
import pandas as pd
from tqdm import tqdm
import json
import time
import warnings
warnings.filterwarnings('ignore')

print("✓ Libraries imported")

# Cell 3: Load Audio Files (SAME AS ORIGINAL)
# This is the KEY ADDITION - you need to recreate audio_files list

dataset_path = '/content/drive/MyDrive/cse425 datasets/FMA_Dataset'
audio_base_path = os.path.join(dataset_path, 'fma_small')

# Get all audio files from folders 050 to 100
audio_files = []
folder_range = range(50, 101)  # 050 to 100

print("Scanning folders 050 to 100...")
for folder_num in tqdm(folder_range):
    folder_name = f"{folder_num:03d}"
    folder_path = os.path.join(audio_base_path, folder_name)

    if os.path.exists(folder_path):
        for file in os.listdir(folder_path):
            if file.endswith('.mp3'):
                audio_files.append(os.path.join(folder_path, file))

print(f"\n✓ Total audio files found: {len(audio_files)}")
print(f"Sample files:")
for i in range(min(3, len(audio_files))):
    print(f"  {i+1}. {audio_files[i]}")

# Cell 4: Load Whisper Model
model_size = "base"  # Change to 'small' if needed
print(f"Loading Whisper '{model_size}' model...")

whisper_model = whisper.load_model(model_size)

print(f"✓ Whisper model loaded!")

# Cell 5: Define Extraction Function
def extract_lyrics_from_audio(audio_path, model, language="en"):
    """Extract lyrics from audio file using Whisper"""
    try:
        result = model.transcribe(
            audio_path,
            language=language,
            fp16=False,
            verbose=False
        )
        return result["text"].strip()
    except Exception as e:
        print(f"Error: {str(e)}")
        return None

# Test
print("Testing on first file...")
test_lyrics = extract_lyrics_from_audio(audio_files[0], whisper_model)
print(f"✓ Test successful!")
print(f"Preview: {test_lyrics[:200]}...")

# Cell 6: Extract All Lyrics
print("=" * 70)
print("EXTRACTING LYRICS FROM ALL AUDIO FILES")
print("=" * 70)

lyrics_save_path = '/content/drive/MyDrive/cse425 datasets/extracted_lyrics'
os.makedirs(lyrics_save_path, exist_ok=True)

all_lyrics = []
failed_files = []

for idx, audio_file in enumerate(tqdm(audio_files, desc="Extracting lyrics")):
    try:
        lyrics = extract_lyrics_from_audio(audio_file, whisper_model)

        if lyrics:
            audio_filename = os.path.basename(audio_file)
            folder = os.path.basename(os.path.dirname(audio_file))

            # Save individual file
            lyrics_filename = audio_filename.replace('.mp3', '.txt')
            lyrics_filepath = os.path.join(lyrics_save_path, f"{folder}_{lyrics_filename}")

            with open(lyrics_filepath, 'w', encoding='utf-8') as f:
                f.write(lyrics)

            all_lyrics.append({
                'audio_file': audio_file,
                'folder': folder,
                'filename': audio_filename,
                'lyrics': lyrics,
                'lyrics_file': lyrics_filepath,
                'word_count': len(lyrics.split())
            })
        else:
            failed_files.append(audio_file)

    except Exception as e:
        print(f"\nError: {str(e)}")
        failed_files.append(audio_file)

print(f"\n✓ Completed: {len(all_lyrics)}/{len(audio_files)}")

import matplotlib.pyplot as plt
import seaborn as sns
lyrics_df = pd.DataFrame(all_lyrics)

print("LYRICS STATISTICS:")
print("=" * 70)
print(f"Songs with lyrics: {len(lyrics_df)}")

# Cell 7: Save Results
lyrics_df = pd.DataFrame(all_lyrics)

# Save CSV
lyrics_csv_path = '/content/drive/MyDrive/cse425 datasets/lyrics_data.csv'
lyrics_df.to_csv(lyrics_csv_path, index=False)

# Save JSON
lyrics_json_path = '/content/drive/MyDrive/cse425 datasets/lyrics_data.json'
lyrics_df.to_json(lyrics_json_path, orient='records', indent=2)

# Save pickle for easy loading
import pickle
lyrics_pickle_path = '/content/drive/MyDrive/cse425 datasets/lyrics_data.pkl'
with open(lyrics_pickle_path, 'wb') as f:
    pickle.dump(lyrics_df, f)

print("=" * 70)
print("✓ ALL RESULTS SAVED!")
print("=" * 70)
print(f"1. CSV: {lyrics_csv_path}")
print(f"2. JSON: {lyrics_json_path}")
print(f"3. Pickle: {lyrics_pickle_path}")
print(f"4. Individual files: {lyrics_save_path}/")
print()
print(f"Total lyrics extracted: {len(lyrics_df)}")
print(f"Total words: {lyrics_df['word_count'].sum():,}")

# Cell 8: Statistics and Visualization
import matplotlib.pyplot as plt
import seaborn as sns

print("LYRICS STATISTICS:")
print("=" * 70)
print(f"Songs with lyrics: {len(lyrics_df)}")
print(f"Total words: {lyrics_df['word_count'].sum():,}")
print(f"Average words/song: {lyrics_df['word_count'].mean():.1f}")
print(f"Median words/song: {lyrics_df['word_count'].median():.1f}")

# Visualize
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Word count distribution
axes[0].hist(lyrics_df['word_count'], bins=30, color='skyblue', edgecolor='black')
axes[0].set_xlabel('Word Count')
axes[0].set_ylabel('Frequency')
axes[0].set_title('Distribution of Lyrics Word Counts', fontweight='bold')
axes[0].grid(alpha=0.3)

# Top folders
top_folders = lyrics_df['folder'].value_counts().head(10)
axes[1].barh(range(len(top_folders)), top_folders.values, color='coral')
axes[1].set_yticks(range(len(top_folders)))
axes[1].set_yticklabels(top_folders.index)
axes[1].set_xlabel('Number of Songs')
axes[1].set_title('Top 10 Folders', fontweight='bold')
axes[1].grid(alpha=0.3, axis='x')

plt.tight_layout()
plt.show()

# Show samples
print("\n" + "=" * 70)
print("SAMPLE LYRICS:")
print("=" * 70)
for i in range(min(3, len(lyrics_df))):
    print(f"\n{i+1}. {lyrics_df.iloc[i]['filename']}")
    print(f"   Words: {lyrics_df.iloc[i]['word_count']}")
    print(f"   Preview: {lyrics_df.iloc[i]['lyrics'][:200]}...")
    print("-" * 70)